# OSX agents don't have nvm pre-installed, and installing it manually
# gives a lot more control over testing packaging options
language: ruby
cache:
  bundler: true

env:
  global:
    - MB_SLOW_TEST_TIMEOUT=6000

# Roughly ordered slowest to fastest to kick off the slow jobs first,
# except include nodes that trigger other CIs in first 5 since they start in parallel
matrix:
  include:
    - os: osx
      sudo: true
      env:
        - MB_GRUNT_TASK='dist version test:pkg deploy:s3'
    - os: osx
      sudo: false
      env:
        - MB_GRUNT_TASK='dist version test:tarball:x64 deploy:s3'

install:
  - export NODE_VERSION=${NODE_VERSION:-8} # Default node version = LTS version
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  - bundle install --without development

script:
  - ./build $MB_GRUNT_TASK
