# OSX agents don't have nvm pre-installed, and installing it manually
# gives a lot more control over testing packaging options
language: ruby
cache:
  bundler: true

env:
  global:
    - MB_SLOW_TEST_TIMEOUT=6000

matrix:
  include:
    - os: osx
      sudo: true
      env:
        - MB_GRUNT_TASK='dist version test:pkg deploy:s3'
    - os: osx
      sudo: false
      env:
        - MB_GRUNT_TASK='dist version test:tarball:x64 deploy:s3'
    - os: osx
      sudo: false
      env:
        - MB_GRUNT_TASK='dist version outOfProcessImposters test'

install:
  - export NODE_VERSION=${NODE_VERSION:-10} # Default node version = LTS version
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
  # Temporary hack; latest version of dpl fails s3 build on Travis
  - echo gem \"aws-sdk\" >> Gemfile
  - echo gem \"mime-types\" >> Gemfile
  - mv Gemfile.lock Gemfile.lock.orig
  - sed -E -e 's/dpl \(1.10.6\)/dpl (1.8.47)/' Gemfile.lock.orig > Gemfile.lock
  # fpm install started failing even after bundle update
  - ruby --version
  - gem install fpm
  - gem install bundler
  - bundle install --without development

script:
  - ./build $MB_GRUNT_TASK
