version: '{build}'

shallow_clone: true

os:
  - Windows Server 2012

platform:
  - x64

environment:
  global:
    MB_SLOW_TEST_TIMEOUT: 45000

  matrix:
    - MB_APPVEYOR_CONFIG: "NODE_VERSION=8|MB_PORT=3535"
    - MB_APPVEYOR_CONFIG: "NODE_VERSION=6|MB_INSTALL_ZIP=true|MB_EXECUTABLE=..\\.mb-test-dir\\mountebank-vMB_VERSION-win-x64\\mb.cmd|MB_PORT=3535"

cache:
  - node_modules -> package.json

init:
  - git config --global core.autocrlf true

install:
  - ps: |
          $version = Get-ChildItem env:MB_VERSION
          ForEach ($var in (Get-ChildItem env:MB_APPVEYOR_CONFIG).Value.Split("|")) {
              $key = $var.Split("=")[0]
              $value = $var.Split("=")[1].Replace("MB_VERSION", $version.Value);
              Set-Item env:$key $value
          }
  - ps: Install-Product node $env:NODE_VERSION
  # This is part of the Windows hack working around ECONNRESET errors by splitting up the test runs
  # I'd prefer just setting the MB_GRUNT_TASK in the matrix and passing that to build.bat
  - call npm install
  - if %MB_INSTALL_ZIP%=="true" (echo Installing zipfile...)
  - if %MB_INSTALL_ZIP%=="true" (node node_modules\grunt-cli\bin\grunt download:zip install:zip)

build_script:
  - node --version && npm --version
  - build.bat test:functionalHttp test:functionalHttps test:functionalSmtp test:functionalTcp
  - build.bat test:functionalApi test:functionalCli test:functionalHtml

test: off
