version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: ./circlebuild default dist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
        # Ignore src; use dist for all downstream jobs, but keep enough to run tests
          root: .
          paths:
            - functionalTest
            - performanceTest
            - test
            - tasks
            - dist
            - Gruntfile.js
            - node_modules
            - scripts
            - circlebuild

  package:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - attach_workspace:
          at: .
      - run: ls -al

  performance:
    docker:
      - image: circleci/node:8.9.4-stretch
    environment:
      - MB_EXECUTABLE: dist/mountebank/bin/mb
    steps:
      - attach_workspace:
          at: .
      - run: ./circlebuild test:performance

workflows:
  version: 2
  full_build:
    jobs:
      - build
      - package:
          requires:
            - build
      - performance:
          requires:
            - build
