version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: ./circlebuild default dist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: dist
          paths:
            - .

  package:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - checkout
      - attach_workspace:
          - at: dist
      - ls -al dist

workflows:
  version: 2
  full_build:
    jobs:
      - build
      - package:
          requires:
            - build
