version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: ./circlebuild lint test dist version
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
        # Ignore src; use dist for all downstream jobs, but keep enough to run tests
          root: .
          paths:
            - functionalTest
            - performanceTest
            - test
            - tasks
            - dist
            - Gruntfile.js
            - node_modules
            - scripts
            - circlebuild
            - firebase.json
            - .jsdoc

  package-tarball:
    docker:
      - image: circleci/node:8.9.4-stretch
    environment:
      - MB_SLOW_TEST_TIMEOUT: 6000
      - MB_PORT: 3535
    steps:
      - attach_workspace:
          at: .
      - run: ruby -v
      - run: bundle install --without development
      - run: node_modules/grunt-cli/bin/grunt test:tarball:x64 deploy:s3

  package-npm:
    docker:
      - image: circleci/node:8.9.4-stretch
    environment:
      - MB_SLOW_TEST_TIMEOUT: 6000
      - MB_PORT: 3535
    steps:
      - attach_workspace:
          at: .
      - run: node_modules/grunt-cli/bin/grunt test:npm
      - run: ls -al dist

  performance:
    docker:
      - image: circleci/node:8.9.4-stretch
    environment:
      - MB_EXECUTABLE: /home/circleci/project/dist/mountebank/bin/mb
    steps:
      - attach_workspace:
          at: .
      - run: node_modules/grunt-cli/bin/grunt test:performance

  docs:
    docker:
      - image: circleci/node:8.9.4-stretch
    steps:
      - attach_workspace:
          at: .
      - run: node_modules/grunt-cli/bin/grunt jsdoc deploy:docs

workflows:
  version: 2
  full_build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - package-tarball:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - package-npm:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - performance:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
      - docs:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
