version: 2.0

jobs:
  build:
    docker:
      - image: bbyars/mountebank-base-build:v1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: ./circlebuild
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
